@Backend_HostAddress = https://localhost:7214
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjRhM2ZlMDI1LTI2MmMtNGJkYS04MWViLWJiMDdmZjA1MDI1ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3NzYzOTYxMDQsImlzcyI6Im15QXBwIiwiYXVkIjoibXlBcHBVc2VyIn0.AgBp-KiqDAjcNJCZPcEngiPcdWuIXZdI9bm7SucOm7Y

### Register User
POST {{Backend_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test10@test.com",
  "password": "123456a",
  "confirmPassword": "123456a",
  "role" : "patient"
}


### Login User
POST {{Backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test10@test.com",
  "password": "123456a"
}


###Create Appointment
POST {{Backend_HostAddress}}/api/appointments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "providerId": "1DF0E3AD-676E-4012-9E27-51B1B99D93A3",
  "slotDateTime": "2026-04-20T14:00:00",
  "visitReason": "Checkup"
}